---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php8.1
  name: phpcs
- commands:
  - vendor/bin/phan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1-ast
  name: phan
- commands:
  - vendor/bin/phpstan analyse src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: 16deb0bb7f519b60e59f79cfadd8828ca8aaad4472f39eb8a9080fdbbd898d88

...
