---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php8.1
  name: phpcs
- commands:
  - vendor/bin/phan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1-ast
  name: phan
- commands:
  - ./vendor/bin/phpstan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: 04467ebe4113c222a797ae5747e9c34fae50dfc1d14c9e8e16df818c1017dee9

...
